version: '3'
services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - ./mongodb:/data/db
        networks:
            - mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        depends_on:
            - mongo
        ports:
            - 8081:8081
        networks:
            - mongo
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: pass
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: pass
networks:
    mongo: